export enum MovieTypes {
    GET_UPCOMING_REQUEST = 'movie/GET_UPCOMING_REQUEST',
    GET_UPCOMING_SUCCESS = 'movie/GET_UPCOMING_SUCCESS',
    GET_NOW_PLAYING_REQUEST = 'movie/GET_NOW_PLAYING_REQUEST',
    GET_NOW_PLAYING_SUCCESS = 'movie/GET_NOW_PLAYING_SUCCESS',
}
